// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceA/a.proto

package serviceA // import "saturn-sonic/test/pb/serviceA"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import serviceB "saturn-sonic/test/pb/serviceB"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloResponse struct {
	Bar                  *serviceB.BarType `protobuf:"bytes,1,opt,name=bar" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_ba68ca161e6888fd, []int{0}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetBar() *serviceB.BarType {
	if m != nil {
		return m.Bar
	}
	return nil
}

type HelloRequest struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_ba68ca161e6888fd, []int{1}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloResponse)(nil), "q.serviceA.HelloResponse")
	proto.RegisterType((*HelloRequest)(nil), "q.serviceA.HelloRequest")
}

func init() { proto.RegisterFile("serviceA/a.proto", fileDescriptor_a_ba68ca161e6888fd) }

var fileDescriptor_a_ba68ca161e6888fd = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x75, 0xd4, 0x4f, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0xd4,
	0x83, 0x89, 0x49, 0xc1, 0x64, 0x9d, 0xf4, 0x93, 0x20, 0xb2, 0x4a, 0x66, 0x5c, 0xbc, 0x1e, 0xa9,
	0x39, 0x39, 0xf9, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xaa, 0x5c, 0xcc, 0x49,
	0x89, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0x70, 0xcd, 0x4e, 0x7a, 0x4e,
	0x89, 0x45, 0x21, 0x95, 0x05, 0xa9, 0x41, 0x20, 0x79, 0x25, 0x05, 0x2e, 0x1e, 0xa8, 0xbe, 0xc2,
	0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xb4, 0xfc, 0x7c, 0xb0, 0x36, 0xce, 0x20, 0x10,
	0xd3, 0x49, 0x3e, 0x4a, 0xb6, 0x38, 0xb1, 0xa4, 0xb4, 0x28, 0x4f, 0xb7, 0x38, 0x3f, 0x2f, 0x33,
	0x59, 0xbf, 0x24, 0xb5, 0xb8, 0x44, 0xbf, 0x20, 0x49, 0x1f, 0xe6, 0x98, 0x24, 0x36, 0xb0, 0x0b,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x90, 0x42, 0x94, 0xb3, 0x00, 0x00, 0x00,
}
