// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceB/b.proto

package serviceB // import "saturn-sonic/test/pb/serviceB"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BarType struct {
	Bar                  string   `protobuf:"bytes,1,opt,name=Bar" json:"Bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarType) Reset()         { *m = BarType{} }
func (m *BarType) String() string { return proto.CompactTextString(m) }
func (*BarType) ProtoMessage()    {}
func (*BarType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b_a09b4068a9c473a5, []int{0}
}
func (m *BarType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarType.Unmarshal(m, b)
}
func (m *BarType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarType.Marshal(b, m, deterministic)
}
func (dst *BarType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarType.Merge(dst, src)
}
func (m *BarType) XXX_Size() int {
	return xxx_messageInfo_BarType.Size(m)
}
func (m *BarType) XXX_DiscardUnknown() {
	xxx_messageInfo_BarType.DiscardUnknown(m)
}

var xxx_messageInfo_BarType proto.InternalMessageInfo

func (m *BarType) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func init() {
	proto.RegisterType((*BarType)(nil), "q.serviceB.BarType")
}

func init() { proto.RegisterFile("serviceB/b.proto", fileDescriptor_b_a09b4068a9c473a5) }

var fileDescriptor_b_a09b4068a9c473a5 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x75, 0xd2, 0x4f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0xd4,
	0x83, 0x89, 0x29, 0x49, 0x73, 0xb1, 0x3b, 0x25, 0x16, 0x85, 0x54, 0x16, 0xa4, 0x0a, 0x09, 0x70,
	0x31, 0x3b, 0x25, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4e, 0xf2, 0x51,
	0xb2, 0xc5, 0x89, 0x25, 0xa5, 0x45, 0x79, 0xba, 0xc5, 0xf9, 0x79, 0x99, 0xc9, 0xfa, 0x25, 0xa9,
	0xc5, 0x25, 0xfa, 0x05, 0x49, 0xfa, 0x30, 0xdd, 0x49, 0x6c, 0x60, 0x03, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0x9f, 0x04, 0xb8, 0x64, 0x00, 0x00, 0x00,
}
